---
title: "git_01"
author: "Salena Bennett"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
THERE are certain things - as, a spider, a ghost,  
The income-tax, gout, an umbrella for three -  
That I hate, but the thing that I hate the most  
Is a thing they call the Sea.  
  
Pour some salt water over the floor -  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
Look what it is to have forgotten  
the torn coat of  “Vecchia Zimarra”  
from Puccini’s  La bohème and to remember  
the other coats from Mt. Horeb on down,  
and look what it is to give your own coat away,  
  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
  
The sea was wet as wet could be,  
      The sands were dry as dry.  
You could not see a cloud, because  
      No cloud was in the sky:  
No birds were flying overhead —  
      There were no birds to fly.  
  
The Walrus and the Carpenter  
      Were walking close at hand;  
They wept like anything to see  
      Such quantities of sand:  
If this were only cleared away,'  
      They said, it would be grand!'  
  
